{
  "formatVersion": "1.1",
  "component": {
    "group": "org.seage",
    "module": "seage-misc",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "seage-misc-1.0.0-SNAPSHOT.jar",
          "url": "seage-misc-1.0.0-SNAPSHOT.jar",
          "size": 95464,
          "sha512": "a0eebb1c78d5d01b4d4a7df6c2bc01c51565fe617550108e0e5df060ef838507de694b6fed6ac572a82307d1d359e7aeec5c9517454b190ab7604bd2ed93fb1e",
          "sha256": "bab619f5ae241f9e066d183f468ae12cdc7f1e550725692d0195af6ce44b9b76",
          "sha1": "ee68ce454f50e251e85274f9c37f458162aecf1b",
          "md5": "8344bdfe1391cd9c682abe5d96f8870a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "net.mahdilamb",
          "module": "colormap",
          "version": {
            "requires": "0.9.61"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20220320"
          }
        }
      ],
      "files": [
        {
          "name": "seage-misc-1.0.0-SNAPSHOT.jar",
          "url": "seage-misc-1.0.0-SNAPSHOT.jar",
          "size": 95464,
          "sha512": "a0eebb1c78d5d01b4d4a7df6c2bc01c51565fe617550108e0e5df060ef838507de694b6fed6ac572a82307d1d359e7aeec5c9517454b190ab7604bd2ed93fb1e",
          "sha256": "bab619f5ae241f9e066d183f468ae12cdc7f1e550725692d0195af6ce44b9b76",
          "sha1": "ee68ce454f50e251e85274f9c37f458162aecf1b",
          "md5": "8344bdfe1391cd9c682abe5d96f8870a"
        }
      ]
    }
  ]
}
