{
  "formatVersion": "1.1",
  "component": {
    "group": "org.seage",
    "module": "seage-aal",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "seage-aal-1.0.0-SNAPSHOT.jar",
          "url": "seage-aal-1.0.0-SNAPSHOT.jar",
          "size": 70384,
          "sha512": "09d412e65b8772f69ee4e557026c9be86babb0591c87858ba99b9aa7f5664e45014b0f994540061766bc2dcfcc16b7c0156f27ad8a09d44ec5eae6375b90d475",
          "sha256": "c0c85c1133de603054cf2174bf90fa33d5168e681d88148829036f8f8f331172",
          "sha1": "c3b302d624aa771b407a8a3c7acc33c66277a4cf",
          "md5": "e1f58d782a94ca09d249cd71d091d548"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.78"
          }
        },
        {
          "group": "com.hubspot.jinjava",
          "module": "jinjava",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "net.mahdilamb",
          "module": "colormap",
          "version": {
            "requires": "0.9.61"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20220320"
          }
        },
        {
          "group": "seage",
          "module": "seage-metaheuristics",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "seage",
          "module": "seage-misc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "seage-aal-1.0.0-SNAPSHOT.jar",
          "url": "seage-aal-1.0.0-SNAPSHOT.jar",
          "size": 70384,
          "sha512": "09d412e65b8772f69ee4e557026c9be86babb0591c87858ba99b9aa7f5664e45014b0f994540061766bc2dcfcc16b7c0156f27ad8a09d44ec5eae6375b90d475",
          "sha256": "c0c85c1133de603054cf2174bf90fa33d5168e681d88148829036f8f8f331172",
          "sha1": "c3b302d624aa771b407a8a3c7acc33c66277a4cf",
          "md5": "e1f58d782a94ca09d249cd71d091d548"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.seage",
          "module": "seage-aal",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "seage-aal-1.0.0-SNAPSHOT-test-fixtures.jar",
          "url": "seage-aal-1.0.0-SNAPSHOT-test-fixtures.jar",
          "size": 11597,
          "sha512": "26cf4b94749081e33d839fb35f140d5fd4a8ce39b391cfab2b9bb9c285abfcb69b430bcc45b3cce30be4595e7a3b88326fd293119f9739626e4deee09932ded5",
          "sha256": "11ac8b7cb2a3ed591ca66cb4915c6d9591c15e97d4ee10d8ac633b60a033fd1f",
          "sha1": "d33f4b36e60d2244624197cc673d322cfc8c75d5",
          "md5": "28c5b55dd7c35108d234e6ac4ff181ee"
        }
      ],
      "capabilities": [
        {
          "group": "seage",
          "name": "seage-aal-test-fixtures",
          "version": "1.0.0-SNAPSHOT"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "seage",
          "module": "seage-metaheuristics",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "seage",
          "module": "seage-misc",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.seage",
          "module": "seage-aal",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "seage-aal-1.0.0-SNAPSHOT-test-fixtures.jar",
          "url": "seage-aal-1.0.0-SNAPSHOT-test-fixtures.jar",
          "size": 11597,
          "sha512": "26cf4b94749081e33d839fb35f140d5fd4a8ce39b391cfab2b9bb9c285abfcb69b430bcc45b3cce30be4595e7a3b88326fd293119f9739626e4deee09932ded5",
          "sha256": "11ac8b7cb2a3ed591ca66cb4915c6d9591c15e97d4ee10d8ac633b60a033fd1f",
          "sha1": "d33f4b36e60d2244624197cc673d322cfc8c75d5",
          "md5": "28c5b55dd7c35108d234e6ac4ff181ee"
        }
      ],
      "capabilities": [
        {
          "group": "seage",
          "name": "seage-aal-test-fixtures",
          "version": "1.0.0-SNAPSHOT"
        }
      ]
    }
  ]
}
